Chapter06/Models/ContactModel.cs
using Microsoft.AspNetCore.Mvc;
using System;

namespace chapter06.Models
{
    [ModelMetadataType(typeof(ContactModelMetadata))]
    [Bind("Email", "WorkEmail", "Birthday", "Gender")]
    public class ContactModel
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string WorkEmail { get; set; }
        public DateTime? Birthday { get; set; }
        public string Gender { get; set; }
        public bool IsActive { get; set; } = true;
        public Location Location { get; set; }
    }
}

Chapter06/Models/ContactModelMetadata.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.ComponentModel.DataAnnotations;

namespace chapter06.Models
{
    internal abstract class ContactModelMetadata
    {
        [HiddenInput(DisplayValue = false)]
        public int Id { get; set; }
        [EmailAddress]
        [Required]
        [CustomValidation(typeof(ValidationMethods), "ValidateEmail")]
        public string Email { get; set; }
        [Display(Name = "Work Email", Description = "The work email", Prompt = "Please enter the work email")]
        [EmailAddress]
        public string WorkEmail { get; set; }
        [DisplayFormat(NullDisplayText = "No birthday supplied", DataFormatString = "{0:yyyyMMdd}")]
        [DataType(DataType.Date)]
        public DateTime? Birthday { get; set; }
        [ModelBinder(typeof(GenderModelBinder), Name = "Gender")]
        [Display(Name = "Gender")]
        public string Gender { get; set; }
        [HiddenInput(DisplayValue = false)]
        public bool IsActive { get; set; }
        [UIHint("Location")]
        public Location Location { get; set; }
    }
}

Chapter06/Models/Gender.cs
namespace chapter06.Models
{
    public enum Gender
    {
        Unspecified = 0,
        Male,
        Female
    }
}

Chapter06/Models/GenderModelBinder.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Threading.Tasks;

namespace chapter06.Models
{
    public class GenderModelBinder : IModelBinder
    {
        public Task BindModelAsync(ModelBindingContext bindingContext)
        {
            var modelName = bindingContext.ModelName;

            var valueProviderResult = bindingContext.ValueProvider.GetValue(modelName);

            if (valueProviderResult != ValueProviderResult.None)
            {
                bindingContext.ModelState.SetModelValue(modelName, valueProviderResult);

                var value = valueProviderResult.FirstValue;

                if (!string.IsNullOrWhiteSpace(value))
                {
                    if (Enum.TryParse<Gender>(value, true, out var gender))
                    {
                        bindingContext.Result = ModelBindingResult.Success(gender.ToString());
                    }
                    else
                    {
                        bindingContext.ModelState.TryAddModelError(modelName, "Invalid gender.");
                    }
                }
            }

            return Task.CompletedTask;
        }
    }
}

Chapter06/Models/Location.cs
namespace chapter06.Models
{
    public class Location
    {
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
    }
}

Chapter06/Models/ProductOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace chapter06.Models
{
    public class ProductOrder : IValidatableObject
    {
        public int Id { get; set; }
        public DateTime Timestamp { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext context)
        {
            if (this.Id <= 0)
            {
                yield return new ValidationResult("Missing id", new[] { "Id" });
            }

            if (this.ProductId <= 0)
            {
                yield return new ValidationResult("Invalid product", new[] { "ProductId" });
            }

            if (this.Quantity <= 0)
            {
                yield return new ValidationResult("Invalid quantity", new[] { "Quantity" });
            }

            if (this.Timestamp > DateTime.Now)
            {
                yield return new ValidationResult("Order date is in the future", new[] { "Timestamp" });
            }
        }
    }
}

Chapter06/Controllers/HomeController.cs
using chapter06.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System;
using System.Linq;

namespace chapter06.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            //create the model

            return View();
        }

        [HttpPost]
        public IActionResult Create(ContactModel model)
        {
            //save the model here

            if (!this.ModelState.IsValid)
            {
                if (this.ModelState["Email"].Errors.Any())
                {
                    var emailErrors = string.Join(Environment.NewLine, this.ModelState["Email"].Errors.Select(e => e.ErrorMessage));

                    return View();
                }
            }


            return RedirectToAction(nameof(Index));
        }

        public IActionResult SetLocation([BindRequired][FromQuery] int x, [BindRequired][FromQuery] int y)
        {
            return Json(new { X = x, Y = y });
        }

        [HttpPost]
        public IActionResult Process([FromBody] dynamic payload)
        {
            return Json(new { Ok = true });
        }
    }
}

Chapter06/Controllers/RepositoryController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace chapter06.Controllers
{
    public class RepositoryController : Controller
    {
        [AcceptVerbs("Get", "Post")]
        public IActionResult CheckEmailExists(string email)
        {
            //if (this._repository.CheckEmailExists(email))
            //{
            //    return this.Json(false);
            //}

            return Json(true);
        }

        [HttpPost("[controller]/[action]")]
        public IActionResult SaveForm(IFormFile file)
        {
            var length = file.Length;
            var name = file.Name;
            //do something with the file
            return View();
        }

        [AjaxOnly]
        public IActionResult AjaxOnly()
        {
            return Json(true);
        }

        public IActionResult Save()
        {
            return View();
        }
    }
}

Chapter06/Views/Home/Create.cshtml
@model chapter06.Models.ContactModel

<div asp-validation-summary="All"></div>

@using (Html.BeginForm("Create", "Home"))
{
    @Html.EditorForModel()

    <fieldset name="Location">
        @Html.EditorFor(x => x.Location)
    </fieldset>
    <button>Submit</button>
}

Chapter06/Views/Home/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Hello, World!</h1>

<form>
    <fieldset>
        <div><label for="name">Name: </label></div>
        <div>
            <input type="text" name="name" id="name" />
            <div><label for="email">Email: </label></div>
            <div>
                <input type="email" name="email" id="email" />
                <div><label for="gender">Gender: </label></div>
                <div>
                    <select name="gender" id="gender">
                        <option>Female</option>
                        <option>Male</option>
                    </select>
                </div>
    </fieldset>
</form>

@using (Html.BeginForm("SaveForm", "Repository", FormMethod.Post,
   new { enctype = "multipart/form-data" }))
{
    <input type="file" name="file" />
    <input type="submit" value="Save" />
}

<script>

$('#submit').click(function(evt) {
  evt.preventDefault();

  var payload = $('form').serialize();

  $.ajax({
    url: '@Url.Action("Save", "Repository")',
    type: 'POST',
    data: payload,
    success: function (result) {
      //success
    },
    error: function (error) {
      //error
    }
    });
  });

</script>

Chapter06/Views/Shared/DisplayTemplates/Location.cshtml
@model chapter06.Models.Location
<div>
    <span>Latitude: @Model.Latitude</span> - <span>Longitude: @Model.Longitude</span>
</div>

Chapter06/Views/Shared/EditorTemplates/Location.cshtml
@model chapter06.Models.Location
<div>
    <span>Latitude: @Html.TextBoxFor(x => x.Latitude)</span>
    <span>Longitude: @Html.TextBoxFor(x => x.Longitude)</span>
</div>