Chapter07/Pages/HelloWorld.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using System.Linq;
using System.Threading.Tasks;

namespace chapter11.Pages
{
    public class HelloWorldModel : PageModel
    {
        public HelloWorldModel(IMyService svc)
        {
        }

        public string Message { get; set; }

        public void OnGet()
        {
            if (this.HttpContext.Request.Headers["HTTP-Referer"].SingleOrDefault()?.Contains("google.com") == true)
            {
                //hey, someone found us through Google!
            }
            
            this.Message = "Hello, World!";
        }

        public async Task<IActionResult> OnPostOneAsync()
        {
            return RedirectToPage("One");
        }

        public IActionResult OnPostTwo()
        {
            return RedirectToPage("Two");
        }

        public void OnPostThree(string foo)
        {
            //
        }

        [NonHandler]
        public void OnGetFoo()
        {
            //nothing
        }
    }
}

Chapter07/Areas/Orders/Pages/Index.cshtml
@page

Chapter07/Pages/HelloWorld.cshtml
@page
@model chapter11.Pages.HelloWorldModel
<!DOCTYPE html>
<html>
<head>
    <title>Hello World</title>
</head>
<body>
    <form method="post">
        <h1>@Html.Raw("Hello, World!")</h1>
        <p>Message: @Model.Message</p>

        <input type="submit" value="One Handler" asp-page-handler="One" />
        <input type="submit" value="Another Handler" asp-page-handler="Two" />
        <input type="submit" value="Yet Another Handler" asp-page-handler="Three" asp-route-foo="bar" />
    </form>
</body>
</html>